
services:
  vihari:
    container_name: backend
    build: ./
    command: gunicorn -b 0.0.0.0:8080 app:app --reload
    working_dir: /usr/vihariApi/
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/vihariApi/
  